name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Flutter manually by specifying the exact version
      - name: Set up Flutter
        run: |
          git clone https://github.com/flutter/flutter.git -b stable --single-branch
          export PATH="$PWD/flutter/bin:$PATH"

      # Check Flutter version to ensure it's installed correctly
      - name: Check Flutter version
        run: flutter --version

      # Accept Android SDK licenses
      - name: Accept Android SDK licenses
        run: yes | flutter doctor --android-licenses

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Run flutter doctor to check for any issues
      - name: Run flutter doctor
        run: flutter doctor

      # Build the Flutter project (modify as needed)
      - name: Build Flutter project
        run: flutter build ios
