name: Flutter Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      # Accept Android SDK licenses
      - name: Accept Android SDK licenses
        run: yes | flutter doctor --android-licenses

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Verify Flutter installation
      - name: Verify Flutter version
        run: flutter --version

      # Run flutter doctor to check environment
      - name: Run flutter doctor
        run: flutter doctor

      # Build Flutter project
      - name: Build Flutter project
        run: flutter build ios
