name: Build Flutter APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y curl git

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: stable

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release
