name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Flutter
      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git -b stable --depth 1
          export PATH="$PATH:`pwd`/flutter/bin"
          flutter doctor

      # Accept Android SDK licenses
      - name: Accept Android SDK licenses
        run: yes | flutter doctor --android-licenses

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Run flutter doctor
      - name: Run flutter doctor
        run: flutter doctor

      # Build the Flutter project
      - name: Build Flutter project
        run: flutter build ios
