name: Flet CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # You can use macos-latest if needed

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # You can choose your preferred version

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          # If you have a specific dependency like flet, you can install it directly
          pip install flet

      # Run tests (if any)
      - name: Run tests
        run: |
          # Assuming you have a test suite, e.g., with pytest
          pytest

      # Run the app (optional, based on your requirements)
      - name: Run Flet app
        run: |
          # Replace `main.py` with your app's entry file
          python main.py
