name: Flutter Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Flutter manually in the user's home directory
      - name: Set up Flutter manually
        run: |
          git clone https://github.com/flutter/flutter.git $HOME/flutter
          echo "$HOME/flutter/bin" >> $GITHUB_PATH  # Add Flutter to PATH
          flutter doctor

      # Accept Android SDK licenses
      - name: Accept Android SDK licenses
        run: flutter doctor --android-licenses

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Run flutter create . (initialize project)
      - name: Run flutter create .
        run: flutter create .

      # Run flutter doctor to check environment
      - name: Run flutter doctor
        run: flutter doctor

      # Build Flutter project
      - name: Build Flutter project
        run: flutter build ios

      # Upload build artifacts (optional)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ios-build
          path: build/ios/iphoneos/Runner.app
