name: Flutter Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Flutter manually and add to PATH
      - name: Set up Flutter
        run: |
          git clone https://github.com/flutter/flutter.git $HOME/flutter
          echo "export PATH=\$PATH:\$HOME/flutter/bin" >> $GITHUB_ENV
          source $GITHUB_ENV  # Ensure the new PATH is loaded
          flutter doctor
          flutter doctor --android-licenses
          flutter pub get
          flutter create .

      # Build Flutter project
      - name: Build Flutter project
        run: flutter build ios

      # Upload build artifacts (optional)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ios-build
          path: build/ios/iphoneos/Runner.app
