name: Flutter Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      # Accept Android SDK licenses
      - name: Accept Android SDK licenses
        run: flutter doctor --android-licenses

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Run Flutter Doctor to check environment
      - name: Run flutter doctor
        run: flutter doctor

      # Run Flutter build
      - name: Build Flutter project
        run: flutter build ios

      # Upload build artifacts (optional, if you want to upload the build output)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ios-build
          path: build/ios/iphoneos/Runner.app
