name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable  # Or specify a specific version like '3.7.0'

      # Accept Android SDK licenses
      - name: Accept Android SDK licenses
        run: yes | flutter doctor --android-licenses

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Run flutter doctor
      - name: Run flutter doctor
        run: flutter doctor

      # Build the Flutter project
      - name: Build Flutter project
        run: flutter build ios
