name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Flutter manually
      - name: Install Flutter
        run: |
          # Install Flutter SDK manually
          git clone https://github.com/flutter/flutter.git -b stable $HOME/flutter
          echo "$HOME/flutter/bin" >> $GITHUB_PATH

      # Check Flutter version
      - name: Check Flutter version
        run: flutter --version

      # Accept Android SDK licenses
      - name: Accept Android SDK licenses
        run: yes | flutter doctor --android-licenses

      # Install dependencies
      - name: Install dependencies
        run: |
          cd path/to/your/flutter/project
          flutter pub get

      # Run flutter doctor to check for any issues
      - name: Run flutter doctor
        run: flutter doctor

      # Build the Flutter project
      - name: Build Flutter project
        run: flutter build ios
